const fs = require('fs');
const path = require('path');

const filePath = '/workspace/ae1205ff-315f-4a05-83d0-9b42ab893b13/sessions/agent_60af3c1d-144a-46ef-9dfc-3153ad0b5c2f/PaperStudio-main/index.html';

let content = fs.readFileSync(filePath, 'utf8');

function replaceAll(str, replacements) {
  for (const [oldStr, newStr] of replacements) {
    if (!str.includes(oldStr)) {
      console.log(`WARNING: String not found: ${oldStr.substring(0, 60)}`);
    }
    str = str.split(oldStr).join(newStr);
  }
  return str;
}

const replacements = [
  ['<html lang="zh-CN">', '<html lang="en">'],
  ["<title>PaperStudio - 打印纸设计工具</title>", "<title>Joe's Studio - Print Paper Design Tool</title>"],
  ['>PaperStudio<', '>Joe\'s Studio<'],
  ['/* 基础滚动条隐藏 */', '/* Basic scrollbar hiding */'],
  ['/* 自定义滚动条样式 */', '/* Custom scrollbar styles */'],
  ['/* UI 交互状态 */', '/* UI interaction states */'],
  ['/* 画布区域背景 */', '/* Canvas area background */'],
  ['/* 禁止背景层拖拽 */', '/* Prevent background layer dragging */'],
  ['/* 模态框与卡片 */', '/* Modal dialogs and cards */'],
  ['/* 光标状态 */', '/* Cursor states */'],
  ['/* 紧凑型表单控件 */', '/* Compact form controls */'],
  ['/* 样式按钮 */', '/* Style buttons */'],
  ['/* 下拉菜单 */', '/* Dropdown menu */'],
  ['/* 表格编辑器 */', '/* Table editor */'],
  ['/* 表格编辑器网格样式 */', '/* Table editor grid styles */'],
  ['/* 选中高亮 */', '/* Selection highlight */'],
  ['/* 悬浮工具栏 */', '/* Floating toolbar */'],
  ['/* 标尺样式 */', '/* Ruler styles */'],
  ['/* ===== 字体搜索下拉组件样式 ===== */', '/* ===== Font search dropdown component styles ===== */'],
  ['/* 打印专用样式 */', '/* Print-specific styles */'],
  ['/* 紧凑模式（用于浮动工具栏，宽度受限） */', '/* Compact mode (for floating toolbar, limited width) */'],
  ['<!-- 字体选择 -->', '<!-- Font Family -->'],
  ['<!-- 字号与加粗 -->', '<!-- Font Size & Bold -->'],
  ['<!-- 边框设置 -->', '<!-- Border -->'],
  ['<!-- 一维码专用选项 -->', '<!-- 1D Barcode Options -->'],
  ['<!-- 标签尺寸 -->', '<!-- Label Dimensions -->'],
  ['>简单的打印纸设计工具<', '>Simple print paper design tool<'],
  ['>新建空白纸<', '>New Blank Paper<'],
  ['>打开纸文件<', '>Open Paper File<'],
  ['>从模板开始<', '>Start from Template<'],
  ['>联系开发者<', '>Contact Developer<'],
  ['alt="联系作者"', 'alt="Contact Author"'],
  ['>扫码添加微信<', '>Scan to Add WeChat<'],
  ['>反馈建议 · 交流<', '>Feedback & Communication<'],
  ['>需要访问权限<', '>Permission Required<'],
  ['>为了读取数据源文件，浏览器需要您的确认。<', '>To read data source files, your browser needs your confirmation.<'],
  ['>取消<', '>Cancel<'],
  ['>授予权限<', '>Grant Permission<'],
  ['>感谢支持<', '>Thanks for Support<'],
  ['alt="微信收款码"', 'alt="WeChat Pay QR Code"'],
  ['>如果觉得工具好用<', '>If you find this tool useful<'],
  ['>欢迎请作者喝杯咖啡，激励持续更新<', '>Feel free to buy the author a coffee to encourage continued updates<'],
  ['>表格编辑器<', '>Table Editor<'],
  ['>拖动分割线调整宽高，选中单元格右键或使用悬浮菜单编辑<', '>Drag dividers to resize, select cell, right-click or use floating menu to edit<'],
  ['title="编辑器视图缩放"', 'title="Editor View Zoom"'],
  ['title="边框宽度"', 'title="Border Width"'],
  ['title="边框颜色"', 'title="Border Color"'],
  ['title="背景颜色"', 'title="Background Color"'],
  ['title="文字颜色"', 'title="Text Color"'],
  ['title="合并"', 'title="Merge"'],
  ['title="拆分"', 'title="Split"'],
  ['title="删除选中行"', 'title="Delete Row"'],
  ['title="删除选中列"', 'title="Delete Column"'],
  ['>行数<', '>Rows<'],
  ['>列数<', '>Columns<'],
  ['>刷新<', '>Refresh<'],
  ['>完成并插入<', '>Done & Insert<'],
  ['>打开<', '>Open<'],
  ['>保存<', '>Save<'],
  ['title="撤销 (Ctrl+Z)"', 'title="Undo (Ctrl+Z)"'],
  ['title="重做 (Ctrl+Y)"', 'title="Redo (Ctrl+Y)"'],
  ['title="插入文字"', 'title="Insert Text"'],
  ['>文字<', '>Text<'],
  ['>段落<', '>Paragraph<'],
  ['>时间<', '>Date/Time<'],
  ['>页码<', '>Page Number<'],
  ['>序列号<', '>Serial Number<'],
  ['>图片<', '>Image<'],
  ['>表格<', '>Table<'],
  ['>条码<', '>Barcode<'],
  ['>图形 <', '>Shapes <'],
  ['>线条<', '>Line<'],
  ['>矩形<', '>Rectangle<'],
  ['>圆形<', '>Circle<'],
  ['>三角形<', '>Triangle<'],
  ['>角形<', '>Star<'],
  ['>菱形<', '>Diamond<'],
  ['>支持作者<', '>Support Author<'],
  ['title="联系作者"', 'title="Contact Author"'],
  ['title="全屏模式"', 'title="Fullscreen"'],
  ['>导出 PDF<', '>Export PDF<'],
  ['>打印<', '>Print<'],
  ['>纸张选项<', '>Paper Options<'],
  ['>纸张尺寸<', '>Paper Size<'],
  ['>Letter 美信<', '>Letter US Letter<'],
  ['>Legal 美长<', '>Legal US Legal<'],
  ['>16开 (210 × 285 mm)<', '>16mo (210 × 285 mm)<'],
  ['>32开 (185 × 260 mm)<', '>32mo (185 × 260 mm)<'],
  ['>方纸 (230 × 230 mm)<', '>Square (230 × 230 mm)<'],
  ['>自定义尺寸…<', '>Custom Size…<'],
  ['>横向<', '>Landscape<'],
  ['title="横向纸张上左右各生成一份相同内容">对开模式<', 'title="Generate duplicate content on left and right sides of landscape paper">Spread Mode<'],
  ['>宽(mm)<', '>Width (mm)<'],
  ['>高(mm)<', '>Height (mm)<'],
  ['>上边距<', '>Top Margin<'],
  ['>下边距<', '>Bottom Margin<'],
  ['>左边距<', '>Left Margin<'],
  ['>右边距<', '>Right Margin<'],
  ['>纸张类型<', '>Paper Type<'],
  ['>空白纸<', '>Blank Paper<'],
  ['>背景颜色<', '>Background Color<'],
  ['title="重置为白色"', 'title="Reset to White"'],
  ['>线条颜色<', '>Line Color<'],
  ['>线宽<', '>Line Width<'],
  ['>标签选项<', '>Label Options<'],
  ['>标签宽(mm)<', '>Label Width (mm)<'],
  ['>标签高(mm)<', '>Label Height (mm)<'],
  ['>横向个数(列)<', '>Count per Row (Columns)<'],
  ['title="自动计算标签尺寸"', 'title="Auto-calculate label size"'],
  ['>纵向个数(行)<', '>Count per Column (Rows)<'],
  ['>横向间距(mm)<', '>Horizontal Gap (mm)<'],
  ['>纵向间距(mm)<', '>Vertical Gap (mm)<'],
  ['>打印份数<', '>Print Quantity<'],
  ['>单张模式<', '>Single Mode<'],
  ['>显示分隔线<', '>Show Separator Lines<'],
  ['>虚线<', '>Dashed<'],
  ['>间距<', '>Spacing<'],
  ['>回字内框宽<', '>Hui Inner Frame Width<'],
  ['>回字内框高<', '>Hui Inner Frame Height<'],
  ['>首行双线<', '>Double Line at First Row<'],
  ['>尾行双线<', '>Double Line at Last Row<'],
  ['>闭合两侧<', '>Close Both Sides<'],
  ['>双线闭合<', '>Double Line Closed<'],
  ['>行线间距 <', '>Line Spacing <'],
  ['>行距偏移 <', '>Line Offset <'],
  ['>格行间距 <', '>Group Line Spacing <'],
  ['>每行格数<', '>Grids per Row<'],
  ['>每组线数<', '>Lines per Staff<'],
  ['>谱表数量<', '>Number of Staves<'],
  ['>行间距(mm)<', '>Line Spacing (mm)<'],
  ['>谱表间距(mm)<', '>Staff Spacing (mm)<'],
  ['>格子大小(mm)<', '>Grid Size (mm)<'],
  ['>中线细度<', '>Inner Line Scale<'],
  ['>内格列数 (竖分)<', '>Inner Grid Columns (Vertical)<'],
  ['>内格行数 (横分)<', '>Inner Grid Rows (Horizontal)<'],
  ['>点密度(mm)<', '>Dot Density (mm)<'],
  ['>圆点直径(mm)<', '>Dot Diameter (mm)<'],
  ['/>隔行错位<', '/>Staggered Rows<'],
  ['>图形边长(mm)<', '>Shape Side Length (mm)<'],
  ['>双线边框<', '>Double Border<'],
  ['title="自适应"', 'title="Auto-fit"'],
  ['title="水平翻转"', 'title="Flip Horizontal"'],
  ['title="垂直翻转"', 'title="Flip Vertical"'],
  ['title="逆时针旋转90°"', 'title="Rotate 90° CCW"'],
  ['title="顺时针旋转90°"', 'title="Rotate 90° CW"'],
  ['title="左移"', 'title="Move Left"'],
  ['title="下移"', 'title="Move Down"'],
  ['title="上移"', 'title="Move Up"'],
  ['title="右移"', 'title="Move Right"'],
  ['title="左对齐于画布"', 'title="Align Left to Canvas"'],
  ['title="水平居中于画布"', 'title="Center Horizontally to Canvas"'],
  ['title="右对齐于画布"', 'title="Align Right to Canvas"'],
  ['title="顶对齐于画布"', 'title="Align Top to Canvas"'],
  ['title="垂直居中于画布"', 'title="Center Vertically to Canvas"'],
  ['title="底对齐于画布"', 'title="Align Bottom to Canvas"'],
  ['title="左对齐"', 'title="Align Left"'],
  ['title="水平居中"', 'title="Center Horizontally"'],
  ['title="右对齐"', 'title="Align Right"'],
  ['title="顶对齐"', 'title="Align Top"'],
  ['title="垂直居中"', 'title="Center Vertically"'],
  ['title="底对齐"', 'title="Align Bottom"'],
  ['title="水平分布"', 'title="Distribute Horizontally"'],
  ['title="垂直分布"', 'title="Distribute Vertically"'],
  ['title="群组 (Ctrl+G)"', 'title="Group (Ctrl+G)"'],
  ['title="解组 (Ctrl+Shift+G)"', 'title="Ungroup (Ctrl+Shift+G)"'],
  ['title="锁定/解锁 (Ctrl+L)"', 'title="Lock/Unlock (Ctrl+L)"'],
  ['title="首条"', 'title="First"'],
  ['title="上一条"', 'title="Previous"'],
  ['title="下一条"', 'title="Next"'],
  ['title="末条"', 'title="Last"'],
  ['title="勾选后，批量打印/导出将只处理当前显示的这一页"', 'title="When checked, batch print/export will only process the currently displayed page"'],
  ['>仅当前页<', '>Current Page Only<'],
  ['>拖动平移 | 滚轮缩放 | Shift+点击 多选 | Alt+拉框 多选<', '>Drag to pan | Scroll to zoom | Shift+Click multi-select | Alt+Drag box select<'],
  ['>预览模式<', '>Preview Mode<'],
  ['>设计模式<', '>Design Mode<'],
  ['>属性<', '>Properties<'],
  ['>图层<', '>Layers<'],
  ['>数据源<', '>Data Source<'],
  ['>选中元素以编辑<', '>Select an element to edit<'],
  ['>静态<', '>Static<'],
  ['>变量<', '>Variable<'],
  ['>序列<', '>Serial<'],
  ['>变量绑定设置<', '>Variable Binding Settings<'],
  ['>请先在"数据源"面板加载 Excel 文件<', '>Please load an Excel file in the "Data Source" panel first<'],
  ['>工作表<', '>Worksheet<'],
  ['>绑定字段<', '>Bind Field<'],
  ['>图片文件夹<', '>Image Folder<'],
  ['>未连接<', '>Not Connected<'],
  ['>选择文件夹...<', '>Select Folder...<'],
  ['>对象属性<', '>Object Properties<'],
  ['title="锁定/解锁"', 'title="Lock/Unlock"'],
  ['>未锁定<', '>Unlocked<'],
  ['>已锁定<', '>Locked<'],
  ['>X 坐标<', '>X Coordinate<'],
  ['>Y 坐标<', '>Y Coordinate<'],
  ['>旋转∠<', '>Rotation ∠<'],
  ['>宽度<', '>Width<'],
  ['>高度<', '>Height<'],
  ['>前缀<', '>Prefix<'],
  ['>后缀<', '>Suffix<'],
  ['>透明度<', '>Opacity<'],
  ['>条码设置<', '>Barcode Settings<'],
  ['>条码类型<', '>Barcode Type<'],
  ['>常用二维码<', '>Common QR Codes<'],
  ['>QR Code (二维码)<', '>QR Code<'],
  ['>Han Xin (汉信码)<', '>Han Xin Code<'],
  ['>常用条形码<', '>Common Barcodes<'],
  ['>物流与供应链<', '>Logistics & Supply Chain<'],
  ['>工业/医疗/其他<', '>Industrial/Medical/Other<'],
  ['>Pharmacode (医药码)<', '>Pharmacode<'],
  ['>邮政码<', '>Postal Codes<'],
  ['>Japan Post (日本邮政)<', '>Japan Post<'],
  ['>KIX (荷兰邮政)<', '>KIX (Netherlands Post)<'],
  ['>内容数据<', '>Content Data<'],
  ['title="引用其他对象的共享数据"', 'title="Reference shared data from other objects"'],
  ['>使用共享字段<', '>Use Shared Field<'],
  ['>条码颜色<', '>Barcode Color<'],
  ['>显示文字<', '>Show Text<'],
  ['>文字位置<', '>Text Position<'],
  ['>条码高度比例<', '>Barcode Height Ratio<'],
  ['>文字大小<', '>Font Size<'],
  ['>文字间距<', '>Text Spacing<'],
  ['>纠错等<', '>Error Correction<'],
  ['>字体<', '>Font Family<'],
  ['title="竖排文字"', 'title="Vertical Text"'],
  ['>行高<', '>Line Height<'],
  ['>字间距<', '>Letter Spacing<'],
  ['>日期时间设置<', '>Date/Time Settings<'],
  ['>显示日期<', '>Show Date<'],
  ['>显示时间<', '>Show Time<'],
  ['>日期格式<', '>Date Format<'],
  ['>时间格式<', '>Time Format<'],
  ['>天数偏移<', '>Day Offset<'],
  ['>分钟偏移<', '>Minute Offset<'],
  ['>页码设置<', '>Page Number Settings<'],
  ['>页码格式<', '>Page Format<'],
  ['>起始页码<', '>Start Page<'],
  ['>序列号设置<', '>Serial Number Settings<'],
  ['>起始值<', '>Start Value<'],
  ['>间隔值<', '>Step Value<'],
  ['>重复次数<', '>Repeat Count<'],
  ['>变化类型<', '>Change Type<'],
  ['>递增<', '>Increment<'],
  ['>递减<', '>Decrement<'],
  ['>生成数量<', '>Generate Count<'],
  ['>预览: <', '>Preview: <'],
  ['>线颜色<', '>Line Color<'],
  ['>线宽<', '>Line Width<'],
  ['>虚线<', '>Dashed<'],
  ['>填充<', '>Fill<'],
  ['title="无填充(透明)"', 'title="No fill (transparent)"'],
  ['>边框颜色<', '>Border Color<'],
  ['>虚线描边<', '>Dashed Stroke<'],
  ['>角类型<', '>Corner Type<'],
  ['>角尺寸<', '>Corner Size<'],
  ['>左上<', '>Top-Left<'],
  ['>右上<', '>Top-Right<'],
  ['>左下<', '>Bottom-Left<'],
  ['>右下<', '>Bottom-Right<'],
  ['>编辑表格<', '>Edit Table<'],
  ['>提示：请使用表格工具调整行列、合并拆分以及单元格样式。<', '>Tip: Use table tools to adjust rows/columns, merge/split, and cell styles.<'],
  ['>替换图片<', '>Replace Image<'],
  ['>设为背景<', '>Set as Background<'],
  ['>铺满页面<', '>Fill Page<'],
  ['>打印/导出时显示<', '>Show When Printing/Exporting<'],
  ['>关闭后，背景图仅在设计时可见，不会被打印或导出为PDF。<', '>When disabled, background image is only visible during design and won\'t be printed or exported as PDF.<'],
  ['>删除背景图片<', '>Delete Background Image<'],
  ['>字段数据共享<', '>Field Data Sharing<'],
  ['>无<', '>None<'],
  ['>共享<', '>Share<'],
  ['>引用<', '>Reference<'],
  ['placeholder="输入共享名 (如: price)"', 'placeholder="Enter shared name (e.g., price)"'],
  ['>选择共享字段<', '>Select Shared Field<'],
  ['>选择已存在共享字段，内容将自动同步。<', '>Select an existing shared field, content will auto-sync.<'],
  ['>导入 Excel 数据<', '>Import Excel Data<'],
  ['>支持 .xlsx / .xls 格式<', '>Supports .xlsx / .xls formats<'],
  ['>选择本地文件<', '>Select Local File<'],
  ['title="文件名"', 'title="File Name"'],
  ['title="断开连接"', 'title="Disconnect"'],
  ['>工作表 (Sheet)<', '>Worksheet (Sheet)<'],
  ['title="重新绑定"', 'title="Rebind"'],
  ['>字段列表<', '>Field List<'],
  ['> 条数据<', '> records<'],
  ['>暂无字段<', '>No fields available<'],
  ['>提示：切换到"属性设置"选中文字，开启"可变数据"以绑定字段。<', '>Tip: Switch to "Properties" panel, select text, enable "Variable Data" to bind fields.<'],
  ['>重新读取文件<', '>Reload File<'],
  ['>正在加载模板...<', '>Loading templates...<'],
  ['e.returnValue = "未保存更改"', 'e.returnValue = "Unsaved changes"'],
  ['return "未保存更改"', 'return "Unsaved changes"'],
  ['"双击编辑文本"', '"Double-click to edit text"'],
  ['"在此输入段落文本...\\n支持自动换行。"', '"Enter paragraph text here...\\nAuto-wrap supported."'],
  ['"时间预览"', '"Date Preview"'],
  ['"____年__月__日"', '"____ Year __ Month __ Day"'],
  ['"第 1 页"', '"Page 1"'],
  ['"第   页"', '"Page   "'],
  ['"第 {page} 页"', '"Page {page}"'],
  ['label: "空白纸"', 'label: "Blank Paper"'],
  ['label: "横线纸"', 'label: "Ruled Paper"'],
  ['label: "方格纸"', 'label: "Grid Paper"'],
  ['label: "作文纸"', 'label: "Composition Paper"'],
  ['label: "英文纸"', 'label: "English Paper"'],
  ['label: "乐谱纸"', 'label: "Music Paper"'],
  ['label: "田字格"', 'label: "Tianzige"'],
  ['label: "米字格"', 'label: "Mizige"'],
  ['label: "回字格"', 'label: "Huizige"'],
  ['label: "宫格纸"', 'label: "Jiugongge"'],
  ['label: "点阵纸"', 'label: "Dot Paper"'],
  ['label: "等距网格"', 'label: "Isometric Grid"'],
  ['label: "六边形网格"', 'label: "Hexagon Grid"'],
  ['label: "标签打印"', 'label: "Label Print"'],
  ['>不绑定数据<', '>Unbound Data<'],
  ['>思源宋体<', '>Source Han Serif CN<'],
  ['>宋体<', '>SimSun<'],
  ['>楷体<', '>KaiTi<'],
  ['>黑体<', '>SimHei<'],
  ['>加载失败<', '>Load Failed<'],
  ['>${filename || "未找到绑定字段"}<', '>${filename || "No bound field found"}<'],
  ['>条码<', '>Barcode<'],
  ['>表格<', '>Table<'],
  ['>文本<', '>Text<'],
  ['>图片<', '>Image<'],
  ['>线条<', '>Line<'],
  ['>形状<', '>Shape<'],
  ['>组合<', '>Group<'],
  ['"【背景】图片"', '"[Background] Image"'],
  ['title="删除"', 'title="Delete"'],
  ['"请按住 Shift 依次点击选择对象进行对齐"', '"Hold Shift and click objects sequentially to align"'],
  ['"至少需要3个元素"', '"At least 3 elements are required"'],
  ['"处理中..."', '"Processing..."'],
  ['"正在渲染PDF.."', '"Rendering PDF..."'],
  ['`正在生成第 ${i + 1} 页...`', '`Generating page ${i + 1}...`'],
  ['"正在保存 PDF..."', '"Saving PDF..."'],
  ['`PDF 导出成功 (${loopCount} 页`)', '`PDF exported successfully (${loopCount} pages)`'],
  ['"设计稿"', '"Design"'],
  ['"项目已保存"', '"Project saved"'],
  ['"项目加载成功"', '"Project loaded successfully"'],
  ['"文件格式错误"', '"Invalid file format"'],
  ['"已粘贴为引用对象"', '"Pasted as reference object"'],
  ['"关联源不存在，已转为静态文本"', '"Association source does not exist, converted to static text"'],
  ['"已取消同步"', '"Sync cancelled"'],
  ['"模板加载失败"', '"Failed to load template"'],
  ['"下载模板..."', '"Downloading template..."'],
  ['"加载失败"', '"Loading failed"'],
  ['"加载中..."', '"Loading..."'],
  ['placeholder="搜索字体…"', 'placeholder="Search fonts..."'],
  ["textContent = '没有匹配的字体'", "textContent = 'No matching fonts found'"],
  ['"无描述"', '"No description"'],
  // JS font map
  ['"simsun", "宋体"', '"simsun", "SimSun"'],
  ['"simhei", "黑体"', '"simhei", "SimHei"'],
  ['"kaiti", "楷体", "kaiti_gb2312"', '"kaiti", "KaiTi", "kaiti_gb2312"'],
  ['"fangsong", "仿宋"', '"fangsong", "FangSong"'],
  // Console/log messages
  ['"无法加载默认字体"', '"Failed to load default font"'],
  ['"检查重复句柄失败，将创建新 ID"', '"Duplicate handle check failed, will create new ID"'],
  ['"TTC 解析失败"', '"TTC parsing failed"'],
  ['"检查重复文件夹句柄失败，将创建新 ID"', '"Duplicate folder handle check failed, will create new ID"'],
  ['"读取文件夹句柄失败"', '"Failed to read folder handle"'],
  ['"打开文件失败"', '"Failed to open file"'],
  ['"文件已失效: "', '"File expired: "'],
  ['"文件读取失败"', '"File read failed"'],
  ['"请先选中一个图片对象"', '"Please select an image object first"'],
  ['"无法访问文件夹"', '"Cannot access folder"'],
  ['"背景图片已移除"', '"Background image removed"'],
  ['"请先选中图片"', '"Please select an image first"'],
  ['"背景已更新"', '"Background updated"'],
  ['"图片已替换"', '"Image replaced"'],
  ['"已设为背景"', '"Set as background"'],
  ['"请先选中一张图片"', '"Please select an image first"'],
  ['" 个对象，', '" objects, '],
  ['" 个锁定对象被保留"', '" locked objects preserved"'],
  ['"所选对象全部已锁定，无法删除"', '"All selected objects are locked, cannot delete"'],
  ['"对象已锁定，无法删除"', '"Object is locked, cannot delete"'],
  ['"创建条码失败: "', '"Failed to create barcode: "'],
  ['"对象已锁定"', '"Object locked"'],
  ['"对象已解锁"', '"Object unlocked"'],
  ['"请先选择单元格"', '"Please select cells first"'],
  ['"至少保留一行"', '"At least one row must be kept"'],
  ['"至少保留一列"', '"At least one column must be kept"'],
  ['"已删除 ', '"Deleted '],
  [' 个对象，', ' objects, '],
  [' 个锁定对象被保留', ' locked objects preserved'],
  ['"请选择至少两个单元格"', '"Please select at least two cells"'],
  ['"请选择矩形区域"', '"Please select a rectangular area"'],
  ['"区域含已合并单元格"', '"Area contains merged cells"'],
  ['"变量预览"', '"Variable Preview"'],
  ['"日期和时间至少显示一项"', '"At least one of date and time must be displayed"'],
  ['"预览: "', '"Preview: "'],
  ['"请按住 Shift 依次点击选择对象进行对齐"', '"Hold Shift and click objects sequentially to align"'],
  ['"至少需要3个元素"', '"At least 3 elements are required"'],
  ['"创建中..."', '"Creating..."'],
  ['"打开中..."', '"Opening..."'],
  ['"首次导出需加载系统字体..."', '"First export needs to load system fonts..."'],
  ['"字体应用到 PDF 失败:"', '"Failed to apply fonts to PDF:"'],
  ['"导出失败: "', '"Export failed: "'],
  ['"打印生成失败: "', '"Print generation failed: "'],
  ['"数据源已更新！"', '"Data source updated!"'],
  ['"已绑定文件夹: "', '"Folder bound: "'],
  ['"无法找到关联文件: "', '"Cannot find associated file: "'],
  ['"无字段"', '"No fields"'],
  ['"已更新"', '"Updated"'],
  ['" 个字段"', '" fields"'],
  ['"未找到可匹配字段或无需更新"', '"No matching fields found or no update needed"'],
  ['"请先加载数据源"', '"Please load data source first"'],
  ['"目标工作表为空或无字段"', '"Target worksheet is empty or has no fields"'],
  ['"请先在"数据源"面板加载 Excel 文件"', '"Please load an Excel file in the "Data Source" panel first"'],
  ['"请先选中图片"', '"Please select an image first"'],
  ['"背景已更新"', '"Background updated"'],
  ['"图片已替换"', '"Image replaced"'],
  ['"已设为背景"', '"Set as background"'],
  ['"请先选中一张图片"', '"Please select an image first"'],
  ['" 个对象，', '" objects, '],
  ['" 个锁定对象被保留"', '" locked objects preserved"'],
  ['"所选对象全部已锁定，无法删除"', '"All selected objects are locked, cannot delete"'],
  ['"对象已锁定，无法删除"', '"Object is locked, cannot delete"'],
  ['"创建条码失败: "', '"Failed to create barcode: "'],
  ['"对象已锁定"', '"Object locked"'],
  ['"对象已解锁"', '"Object unlocked"'],
  ['"请先选择单元格"', '"Please select cells first"'],
  ['"至少保留一行"', '"At least one row must be kept"'],
  ['"至少保留一列"', '"At least one column must be kept"'],
  ['"已删除 ', '"Deleted '],
  [' 个对象，', ' objects, '],
  [' 个锁定对象被保留', ' locked objects preserved'],
  ['"请选择至少两个单元格"', '"Please select at least two cells"'],
  ['"请选择矩形区域"', '"Please select a rectangular area"'],
  ['"区域含已合并单元格"', '"Area contains merged cells"'],
  ['"表格已更新"', '"Table updated"'],
  ['"表格已插入"', '"Table inserted"'],
  ['"变量预览"', '"Variable Preview"'],
  ['"日期和时间至少显示一项"', '"At least one of date and time must be displayed"'],
  ['"预览: "', '"Preview: "'],
  ['"条码"', '"Barcode"'],
  ['"表格"', '"Table"'],
  ['"文本"', '"Text"'],
  ['"图片"', '"Image"'],
  ['"线条"', '"Line"'],
  ['"形状"', '"Shape"'],
  ['"组合"', '"Group"'],
  ['"【背景】图片"', '"[Background] Image"'],
  ['title="删除"', 'title="Delete"'],
  ['"请按住 Shift 依次点击选择对象进行对齐"', '"Hold Shift and click objects sequentially to align"'],
  ['"至少需要3个元素"', '"At least 3 elements are required"'],
  ['"处理中..."', '"Processing..."'],
  ['"正在渲染PDF.."', '"Rendering PDF..."'],
  ['`正在生成第 ${i + 1} 页...`', '`Generating page ${i + 1}...`'],
  ['"正在保存 PDF..."', '"Saving PDF..."'],
  ['`PDF 导出成功 (${loopCount} 页`)', '`PDF exported successfully (${loopCount} pages)`'],
  ['"设计稿"', '"Design"'],
  ['"项目已保存"', '"Project saved"'],
  ['"项目加载成功"', '"Project loaded successfully"'],
  ['"文件格式错误"', '"Invalid file format"'],
  ['"数据解析异常: "', '"Data parsing error: "'],
  ['"已粘贴为引用对象"', '"Pasted as reference object"'],
  ['"关联源不存在，已转为静态文本"', '"Association source does not exist, converted to static text"'],
  ['"已取消同步"', '"Sync cancelled"'],
  ['"模板加载失败"', '"Failed to load template"'],
  ['"下载模板..."', '"Downloading template..."'],
  ['"加载失败"', '"Loading failed"'],
  ['"加载中..."', '"Loading..."'],
  ['"Font Access Error"', '"Font Access Error"'],
  ['"Restore ImgDir Failed"', '"Restore ImgDir Failed"'],
  ['"Load img failed"', '"Load img failed"'],
  ['"VDP Barcode Update Failed:"', '"VDP Barcode Update Failed:"'],
  ['"Label generation: Barcode error"', '"Label generation: Barcode error"'],
  ['"Render Error:"', '"Render Error:"'],
  // Date format display labels
  ['"2024年01月30日"', '"2024-01-30"'],
  ['"2024年01月"', '"2024-01"'],
  ['"01月30日"', '"01-30"'],
  ['"2024年"', '"2024"'],
  ['"30/01/2024 (日月年)"', '"30/01/2024 (DD/MM/YYYY)"'],
  ['"01/30/2024 (月日年)"', '"01/30/2024 (MM/DD/YYYY)"'],
  ['"30-01-2024"', '"30-01-2024"'],
  ['"2024 (仅年)"', '"2024 (Year only)"'],
  ['"01 (仅月)"', '"01 (Month only)"'],
  ['"01月"', '"01 Month"'],
  ['"30 (仅日)"', '"30 (Day only)"'],
  ['"30日"', '"30 Day"'],
  // Time format display labels
  ['"14时30分59秒"', '"14:30:59"'],
  ['"14时30分"', '"14:30"'],
  ['"30分59秒"', '"30min 59s"'],
  ['"14点30分"', '"14:30"'],
  ['"14 (仅时-24)"', '"14 (Hour-24)"'],
  ['"14时"', '"14h"'],
  ['"2 (仅时-12)"', '"2 (Hour-12)"'],
  ['"30 (仅分)"', '"30 (Min only)"'],
  ['"30分"', '"30min"'],
  ['"59 (仅秒)"', '"59 (Sec only)"'],
  ['"59秒"', '"59sec"'],
];

// Sort by length descending
replacements.sort((a, b) => b[0].length - a[0].length);

console.log('Starting translations for index.html...');
const originalLength = content.length;
content = replaceAll(content, replacements);
console.log(`File size changed from ${originalLength} to ${content.length} bytes`);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Done! index.html has been updated.');
