const fs = require('fs');
const path = require('path');

const filePath = '/workspace/ae1205ff-315f-4a05-83d0-9b42ab893b13/sessions/agent_60af3c1d-144a-46ef-9dfc-3153ad0b5c2f/PaperStudio-main/index.html';

let content = fs.readFileSync(filePath, 'utf8');

function replaceAll(str, replacements) {
  for (const [oldStr, newStr] of replacements) {
    if (!str.includes(oldStr)) {
      console.log(`WARNING: String not found: ${oldStr.substring(0, 60)}`);
    }
    str = str.split(oldStr).join(newStr);
  }
  return str;
}

const replacements = [
  // Remaining visible text from script 1
  ['>授予权限<', '>Grant Permission<'],
  ['>表格编辑器<', '>Table Editor<'],
  ['title="字号"', 'title="Font Size"'],
  ['>取消<', '>Cancel<'],
  ['>完成并插入<', '>Done & Insert<'],
  ['>序列号<', '>Serial Number<'],
  ['>纸张选项<', '>Paper Options<'],
  ['>标签选项<', '>Label Options<'],
  ['>属性<', '>Properties<'],
  ['>图层<', '>Layers<'],
  ['>数据源<', '>Data Source<'],
  ['>静态<', '>Static<'],
  ['>变量<', '>Variable<'],
  ['>序列<', '>Serial<'],
  ['>条码设置<', '>Barcode Settings<'],
  ['>常用二维码<', '>Common QR Codes<'],
  ['>常用条形码<', '>Common Barcodes<'],
  ['>物流与供应链<', '>Logistics & Supply Chain<'],
  ['>工业/医疗/其他<', '>Industrial/Medical/Other<'],
  ['>邮政码<', '>Postal Codes<'],
  ['>内容数据<', '>Content Data<'],
  ['title="引用其他对象的共享数据"', 'title="Reference shared data from other objects"'],
  ['>使用共享字段<', '>Use Shared Field<'],
  ['>条码颜色<', '>Barcode Color<'],
  ['>显示文字<', '>Show Text<'],
  ['>文字位置<', '>Text Position<'],
  ['>条码高度比例<', '>Barcode Height Ratio<'],
  ['>文字大小<', '>Font Size<'],
  ['>文字间距<', '>Text Spacing<'],
  ['>纠错等<', '>Error Correction<'],
  ['>字体<', '>Font Family<'],
  ['title="竖排文字"', 'title="Vertical Text"'],
  ['>行高<', '>Line Height<'],
  ['>字间距<', '>Letter Spacing<'],
  ['>日期时间设置<', '>Date/Time Settings<'],
  ['>显示日期<', '>Show Date<'],
  ['>显示时间<', '>Show Time<'],
  ['>日期格式<', '>Date Format<'],
  ['>时间格式<', '>Time Format<'],
  ['>天数偏移<', '>Day Offset<'],
  ['>分钟偏移<', '>Minute Offset<'],
  ['>页码设置<', '>Page Number Settings<'],
  ['>页码格式<', '>Page Format<'],
  ['>起始页码<', '>Start Page<'],
  ['>序列号设置<', '>Serial Number Settings<'],
  ['>起始值<', '>Start Value<'],
  ['>间隔值<', '>Step Value<'],
  ['>重复次数<', '>Repeat Count<'],
  ['>变化类型<', '>Change Type<'],
  ['>递增<', '>Increment<'],
  ['>递减<', '>Decrement<'],
  ['>生成数量<', '>Generate Count<'],
  ['>预览: <', '>Preview: <'],
  ['>线颜色<', '>Line Color<'],
  ['>线宽<', '>Line Width<'],
  ['>虚线<', '>Dashed<'],
  ['>填充<', '>Fill<'],
  ['title="无填充(透明)"', 'title="No fill (transparent)"'],
  ['>边框颜色<', '>Border Color<'],
  ['>虚线描边<', '>Dashed Stroke<'],
  ['>角类型<', '>Corner Type<'],
  ['>角尺寸<', '>Corner Size<'],
  ['>左上<', '>Top-Left<'],
  ['>右上<', '>Top-Right<'],
  ['>左下<', '>Bottom-Left<'],
  ['>右下<', '>Bottom-Right<'],
  ['>编辑表格<', '>Edit Table<'],
  ['>提示：请使用表格工具调整行列、合并拆分以及单元格样式。<', '>Tip: Use table tools to adjust rows/columns, merge/split, and cell styles.<'],
  ['>替换图片<', '>Replace Image<'],
  ['>设为背景<', '>Set as Background<'],
  ['>铺满页面<', '>Fill Page<'],
  ['>打印/导出时显示<', '>Show When Printing/Exporting<'],
  ['>关闭后，背景图仅在设计时可见，不会被打印或导出为PDF。<', '>When disabled, background image is only visible during design and won\'t be printed or exported as PDF.<'],
  ['>删除背景图片<', '>Delete Background Image<'],
  ['>字段数据共享<', '>Field Data Sharing<'],
  ['>无<', '>None<'],
  ['>共享<', '>Share<'],
  ['>引用<', '>Reference<'],
  ['placeholder="输入共享名 (如: price)"', 'placeholder="Enter shared name (e.g., price)"'],
  ['>选择共享字段<', '>Select Shared Field<'],
  ['>选择已存在共享字段，内容将自动同步。<', '>Select an existing shared field, content will auto-sync.<'],
  ['>导入 Excel 数据<', '>Import Excel Data<'],
  ['>支持 .xlsx / .xls 格式<', '>Supports .xlsx / .xls formats<'],
  ['>选择本地文件<', '>Select Local File<'],
  ['title="文件名"', 'title="File Name"'],
  ['title="断开连接"', 'title="Disconnect"'],
  ['>工作表 (Sheet)<', '>Worksheet (Sheet)<'],
  ['title="重新绑定"', 'title="Rebind"'],
  ['>字段列表<', '>Field List<'],
  ['> 条数据<', '> records<'],
  ['>暂无字段<', '>No fields available<'],
  ['>提示：切换到"属性设置"选中文字，开启"可变数据"以绑定字段。<', '>Tip: Switch to "Properties" panel, select text, enable "Variable Data" to bind fields.<'],
  ['>重新读取文件<', '>Reload File<'],
  ['>正在加载模板...<', '>Loading templates...<'],
  ['e.returnValue = "未保存更改"', 'e.returnValue = "Unsaved changes"'],
  ['return "未保存更改"', 'return "Unsaved changes"'],
  ['"双击编辑文本"', '"Double-click to edit text"'],
  ['"在此输入段落文本...\\n支持自动换行。"', '"Enter paragraph text here...\\nAuto-wrap supported."'],
  ['"时间预览"', '"Date Preview"'],
  ['"____年__月__日"', '"____ Year __ Month __ Day"'],
  ['"第 1 页"', '"Page 1"'],
  ['"第   页"', '"Page   "'],
  ['"第 {page} 页"', '"Page {page}"'],

  // Paper defaults
  ['label: "空白纸"', 'label: "Blank Paper"'],
  ['label: "横线纸"', 'label: "Ruled Paper"'],
  ['label: "方格纸"', 'label: "Grid Paper"'],
  ['label: "作文纸"', 'label: "Composition Paper"'],
  ['label: "英文纸"', 'label: "English Paper"'],
  ['label: "乐谱纸"', 'label: "Music Paper"'],
  ['label: "田字格"', 'label: "Tianzige"'],
  ['label: "米字格"', 'label: "Mizige"'],
  ['label: "回字格"', 'label: "Huizige"'],
  ['label: "宫格纸"', 'label: "Jiugongge"'],
  ['label: "点阵纸"', 'label: "Dot Paper"'],
  ['label: "等距网格"', 'label: "Isometric Grid"'],
  ['label: "六边形网格"', 'label: "Hexagon Grid"'],
  ['label: "标签打印"', 'label: "Label Print"'],

  // Select options
  ['>不绑定数据<', '>Unbound Data<'],

  // Font names
  ['>思源宋体<', '>Source Han Serif CN<'],
  ['>宋体<', '>SimSun<'],
  ['>楷体<', '>KaiTi<'],
  ['>黑体<', '>SimHei<'],

  // SVG error text
  ['>加载失败<', '>Load Failed<'],
  ['>${filename || "未找到绑定字段"}<', '>${filename || "No bound field found"}<'],

  // Layer labels
  ['"条码"', '"Barcode"'],
  ['"表格"', '"Table"'],
  ['"文本"', '"Text"'],
  ['"图片"', '"Image"'],
  ['"线条"', '"Line"'],
  ['"形状"', '"Shape"'],
  ['"组合"', '"Group"'],
  ['"【背景】图片"', '"[Background] Image"'],
  ['title="删除"', 'title="Delete"'],

  // Toast and UI messages (JS strings)
  ['"请按住 Shift 依次点击选择对象进行对齐"', '"Hold Shift and click objects sequentially to align"'],
  ['"至少需要3个元素"', '"At least 3 elements are required"'],
  ['"处理中..."', '"Processing..."'],
  ['"正在渲染PDF.."', '"Rendering PDF..."'],
  ['`正在生成第 ${i + 1} 页...`', '`Generating page ${i + 1}...`'],
  ['"正在保存 PDF..."', '"Saving PDF..."'],
  ['`PDF 导出成功 (${loopCount} 页`)', '`PDF exported successfully (${loopCount} pages)`'],
  ['"设计稿"', '"Design"'],
  ['"项目已保存"', '"Project saved"'],
  ['"项目加载成功"', '"Project loaded successfully"'],
  ['"文件格式错误"', '"Invalid file format"'],
  ['"数据解析异常: "', '"Data parsing error: "'],
  ['"已粘贴为引用对象"', '"Pasted as reference object"'],
  ['"关联源不存在，已转为静态文本"', '"Association source does not exist, converted to static text"'],
  ['"已取消同步"', '"Sync cancelled"'],
  ['"模板加载失败"', '"Failed to load template"'],
  ['"下载模板..."', '"Downloading template..."'],
  ['"加载失败"', '"Loading failed"'],
  ['"加载中..."', '"Loading..."'],
  ['"已取消加载数据源"', '"Data source loading cancelled"'],
  ['"文件已失效: "', '"File expired: "'],
  ['" 条数据"', '" records"'],
  ['"行列数必须大于0"', '"Rows and columns must be greater than 0"'],
  ['"计算结果无效，请检查边距或间距设置"', '"Calculation result is invalid, check margin or spacing settings"'],
  ['"特殊组件无法解组"', '"Special component cannot be ungrouped"'],
  ['"已锁定"', '"Locked"'],
  ['"未锁定"', '"Unlocked"'],
  ['"设置图片文件夹..."', '"Set image folder..."'],
  ['"已在预览中删除图层"', '"Layer deleted in preview"'],

  // JS font map
  ['"simsun", "宋体"', '"simsun", "SimSun"'],
  ['"simhei", "黑体"', '"simhei", "SimHei"'],
  ['"kaiti", "楷体", "kaiti_gb2312"', '"kaiti", "KaiTi", "kaiti_gb2312"'],
  ['"fangsong", "仿宋"', '"fangsong", "FangSong"'],

  // Console warnings
  ['"无法加载默认字体"', '"Failed to load default font"'],
  ['"检查重复句柄失败，将创建新 ID"', '"Duplicate handle check failed, will create new ID"'],
  ['"TTC 解析失败"', '"TTC parsing failed"'],
  ['"检查重复文件夹句柄失败，将创建新 ID"', '"Duplicate folder handle check failed, will create new ID"'],
  ['"读取文件夹句柄失败"', '"Failed to read folder handle"'],
  ['"打开文件失败"', '"Failed to open file"'],
  ['"文件读取失败"', '"File read failed"'],
  ['"请先选中一个图片对象"', '"Please select an image object first"'],
  ['"无法访问文件夹"', '"Cannot access folder"'],
  ['"请先选中图片"', '"Please select an image first"'],
  ['"背景已更新"', '"Background updated"'],
  ['"图片已替换"', '"Image replaced"'],
  ['"已设为背景"', '"Set as background"'],
  ['"请先选中一张图片"', '"Please select an image first"'],
  ['" 个对象，', '" objects, '],
  ['" 个锁定对象被保留"', '" locked objects preserved"'],
  ['"所选对象全部已锁定，无法删除"', '"All selected objects are locked, cannot delete"'],
  ['"对象已锁定，无法删除"', '"Object is locked, cannot delete"'],
  ['"创建条码失败: "', '"Failed to create barcode: "'],
  ['"对象已锁定"', '"Object locked"'],
  ['"对象已解锁"', '"Object unlocked"'],
  ['"请先选择单元格"', '"Please select cells first"'],
  ['"至少保留一行"', '"At least one row must be kept"'],
  ['"至少保留一列"', '"At least one column must be kept"'],
  ['"已删除 ', '"Deleted '],
  ['"请选择至少两个单元格"', '"Please select at least two cells"'],
  ['"请选择矩形区域"', '"Please select a rectangular area"'],
  ['"区域含已合并单元格"', '"Area contains merged cells"'],
  ['"表格已更新"', '"Table updated"'],
  ['"表格已插入"', '"Table inserted"'],
  ['"变量预览"', '"Variable Preview"'],
  ['"日期和时间至少显示一项"', '"At least one of date and time must be displayed"'],
  ['"预览: "', '"Preview: "'],
  ['"Sheet switch error:"', '"Sheet switch error:"'],
  ['"无字段"', '"No fields"'],
  ['"已更新"', '"Updated"'],
  ['" 个字段"', '" fields"'],
  ['"未找到可匹配字段或无需更新"', '"No matching fields found or no update needed"'],
  ['"请先加载数据源"', '"Please load data source first"'],
  ['"目标工作表为空或无字段"', '"Target worksheet is empty or has no fields"'],
  ['"Font Access Error"', '"Font Access Error"'],
  ['"Restore ImgDir Failed"', '"Restore ImgDir Failed"'],
  ['"VDP Barcode Update Failed:"', '"VDP Barcode Update Failed:"'],
  ['"Label generation: Barcode error"', '"Label generation: Barcode error"'],
  ['"Render Error:"', '"Render Error:"'],
  ['"请先在"数据源"面板加载 Excel 文件"', '"Please load an Excel file in the "Data Source" panel first"'],
  ['"无法找到关联文件: "', '"Cannot find associated file: "'],
  ['"已绑定文件夹: "', '"Folder bound: "'],
];

// Sort by length descending
replacements.sort((a, b) => b[0].length - a[0].length);

console.log('Starting second pass translations...');
const originalLength = content.length;
content = replaceAll(content, replacements);
console.log(`File size changed from ${originalLength} to ${content.length} bytes`);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Done! Second pass complete.');
